image: Visual Studio 2017

before_build:
  - cmd: dotnet --info
  - cmd: dotnet restore ./GrEmit.sln --verbosity m

build_script:
  - cmd: dotnet build --configuration Release ./GrEmit.sln

test_script:
  - cmd: dotnet test --no-build --configuration Release ./GrEmit.Tests/GrEmit.Tests.csproj --logger "trx;LogFileName=test-results.trx"

after_test:
  - ps: |
      $wc = New-Object 'System.Net.WebClient'
      $url = "https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)";
      $wc.UploadFile($url, (Resolve-Path './GrEmit.Tests/TestResults/test-results.trx'))
